### ISSUE TITLE
Avoid Embedded Scripts

### ISSUE THREAD

**Issue by overlineink** [BeanGreen247/Minimalist-chatbot#1]
In order to make the code more readable, avoid embed big blocks of code within **HTML** markup. I recomend to shift it out to a new file like `bot.js`.

Also check,
[StackOverflow](https://stackoverflow.com/questions/2837921/is-it-bad-practice-to-embed-javascript-into-the-body-of-html) & [Google Docs](https://developers.google.com/speed/docs/insights/BlockingJS) for more details.

**Comment by BeanGreen247** [comment]
Yeah I will look into it  once I have fixed some small issues. And thank you for letting me know. Did not think of that.

**Comment by BeanGreen247** [comment]
All right did as you suggested. I moved bot javascript code into a seperate file.
